version: '3.8'
services:
    api:
        container_name: prediction_api
        build: .
        volumes:
            - ./:/usr/src/app/
            - ../trainer/:/usr/src/app/trainer/
        ports:
            - 5000:5000
        environment:
            PORT: 5000
            FLASK_DEBUG: 1
